# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20161022_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='batch_year',
            field=models.IntegerField(default=2016),
        ),
    ]
